"""initial fapiao warehouse schema

Revision ID: f9172c02c429
Revises: 
Create Date: 2026-05-28 15:59:04.627943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9172c02c429'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('tax_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('alias', sa.Text(), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tax_no')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_no', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=1), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=True),
    sa.Column('raw_response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_tax_no'), 'sync_runs', ['tax_no'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tax_no', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=1), nullable=False),
    sa.Column('sdfphm', sa.String(length=40), nullable=True),
    sa.Column('fphm', sa.String(length=40), nullable=True),
    sa.Column('fpdm', sa.String(length=20), nullable=True),
    sa.Column('xfsbh', sa.String(length=20), nullable=True),
    sa.Column('xfmc', sa.Text(), nullable=True),
    sa.Column('gfsbh', sa.String(length=20), nullable=True),
    sa.Column('gfmc', sa.Text(), nullable=True),
    sa.Column('kprq', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fppz', sa.Text(), nullable=True),
    sa.Column('fpzt', sa.String(length=40), nullable=True),
    sa.Column('fpfxdj', sa.String(length=20), nullable=True),
    sa.Column('sfzsfp', sa.String(length=10), nullable=True),
    sa.Column('jshj', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('je', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('se', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('slv', sa.String(length=20), nullable=True),
    sa.Column('tdywlx', sa.String(length=40), nullable=True),
    sa.Column('bz', sa.Text(), nullable=True),
    sa.Column('kpr', sa.Text(), nullable=True),
    sa.Column('deductible', sa.String(length=10), nullable=True),
    sa.Column('deductible_period', sa.String(length=10), nullable=True),
    sa.Column('raw_section', sa.String(length=40), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=True),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_no', 'data_type', 'sdfphm', name='uq_invoice_natural_key')
    )
    op.create_index('ix_invoice_fppz', 'invoices', ['fppz'], unique=False)
    op.create_index('ix_invoice_fpzt', 'invoices', ['fpzt'], unique=False)
    op.create_index('ix_invoice_gfsbh', 'invoices', ['gfsbh'], unique=False)
    op.create_index('ix_invoice_kprq', 'invoices', ['kprq'], unique=False)
    op.create_index('ix_invoice_tax_no_data_type', 'invoices', ['tax_no', 'data_type'], unique=False)
    op.create_index('ix_invoice_xfsbh', 'invoices', ['xfsbh'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sync_run_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decoded_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('commodity_name', sa.Text(), nullable=True),
    sa.Column('spec', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('qty', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=22, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.String(length=20), nullable=True),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_classify_code', sa.String(length=40), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'row_no', name='uq_invoice_item_row')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_table('raw_payloads')
    op.drop_index('ix_invoice_xfsbh', table_name='invoices')
    op.drop_index('ix_invoice_tax_no_data_type', table_name='invoices')
    op.drop_index('ix_invoice_kprq', table_name='invoices')
    op.drop_index('ix_invoice_gfsbh', table_name='invoices')
    op.drop_index('ix_invoice_fpzt', table_name='invoices')
    op.drop_index('ix_invoice_fppz', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_sync_runs_tax_no'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('companies')
    # ### end Alembic commands ###
